-- ウォレットシードデータ
-- wallets-setup.sql を先に実行してください

INSERT INTO wallets (id, name, name_en, type, description, url, domain, logo_color, chains, features, security_level, trust_score, established, japanese_support, is_free, price_note, notes) VALUES

-- ===== ブラウザ拡張 =====
(
  'metamask',
  'MetaMask',
  'MetaMask',
  'browser_extension',
  '世界最大のEVMウォレット。Ethereum・EVM互換チェーンに対応し、DeFiやNFTの操作が可能。ブラウザ拡張とモバイルアプリを提供。',
  'https://metamask.io',
  'metamask.io',
  '#E8831D',
  ARRAY['EVM'],
  ARRAY['dex_swap','nft','multi_account','browser_ext','mobile_app','ledger_support','trezor_support','wc2','open_source'],
  'medium',
  9,
  2016,
  false,
  true,
  NULL,
  'ConsenSysが開発。2500万人以上のユーザーが利用。'
),
(
  'phantom',
  'Phantom',
  'Phantom',
  'browser_extension',
  'Solana対応の主要ウォレット。NFT・DeFi操作に特化しており、EVMチェーンにも対応。シンプルなUIで初心者にも使いやすい。',
  'https://phantom.app',
  'phantom.app',
  '#AB9FF2',
  ARRAY['SOL','EVM'],
  ARRAY['dex_swap','nft','staking','multi_account','browser_ext','mobile_app','wc2'],
  'medium',
  8,
  2021,
  false,
  true,
  NULL,
  'Solanaエコシステムのデファクトスタンダードウォレット。'
),
(
  'rabby',
  'Rabby Wallet',
  'Rabby Wallet',
  'browser_extension',
  'DeBank製のEVMウォレット。トランザクション事前シミュレーション機能により、フィッシング詐欺やスキャムを事前に検知できるセキュリティ重視設計。',
  'https://rabby.io',
  'rabby.io',
  '#7084FF',
  ARRAY['EVM'],
  ARRAY['dex_swap','nft','multi_account','browser_ext','ledger_support','wc2','open_source'],
  'high',
  9,
  2021,
  false,
  true,
  NULL,
  'DeFiユーザーに人気のセキュリティ重視ウォレット。'
),
(
  'coinbase-wallet',
  'Coinbase Wallet',
  'Coinbase Wallet',
  'browser_extension',
  'Coinbase提供のセルフカストディウォレット。EVM・Solana・BTC等に対応し、DeFi/NFTの操作が可能。Passkey対応でシードフレーズ不要の設定も可能。',
  'https://www.coinbase.com/wallet',
  'coinbase.com',
  '#0052FF',
  ARRAY['EVM','SOL','BTC'],
  ARRAY['dex_swap','nft','staking','browser_ext','mobile_app','wc2','passkey','open_source'],
  'high',
  8,
  2018,
  false,
  true,
  NULL,
  'Coinbase取引所とシームレスに連携可能。'
),

-- ===== モバイル =====
(
  'trust-wallet',
  'Trust Wallet',
  'Trust Wallet',
  'mobile',
  'Binance傘下のマルチチェーンモバイルウォレット。100以上のブロックチェーンに対応し、NFT・DeFi・ステーキングが一元管理できる。',
  'https://trustwallet.com',
  'trustwallet.com',
  '#3375BB',
  ARRAY['EVM','BTC','SOL','COSMOS','NEAR','TRON'],
  ARRAY['dex_swap','nft','staking','multi_account','mobile_app','browser_ext','wc2','open_source'],
  'medium',
  8,
  2017,
  true,
  true,
  NULL,
  'Binance公式ウォレット。日本語対応。'
),
(
  'rainbow',
  'Rainbow',
  'Rainbow',
  'mobile',
  'シンプルで美しいデザインのEVMモバイルウォレット。NFTの表示やDeFi操作に優れ、初心者にも直感的に使えるUIが特徴。',
  'https://rainbow.me',
  'rainbow.me',
  '#FF6B6B',
  ARRAY['EVM'],
  ARRAY['dex_swap','nft','mobile_app','browser_ext','wc2','open_source'],
  'medium',
  7,
  2020,
  false,
  true,
  NULL,
  'デザイン重視のEthereum向けウォレット。'
),
(
  'uniswap-wallet',
  'Uniswap Wallet',
  'Uniswap Wallet',
  'mobile',
  'Uniswap Labsが提供するEVMモバイルウォレット。Uniswapとの深い連携により、シームレスなスワップ操作が可能。シンプルで直感的なUI。',
  'https://wallet.uniswap.org',
  'uniswap.org',
  '#FC72FF',
  ARRAY['EVM'],
  ARRAY['dex_swap','nft','mobile_app','wc2','open_source'],
  'medium',
  7,
  2023,
  false,
  true,
  NULL,
  'Uniswap公式ウォレット。DEXスワップに最適化。'
),

-- ===== ソフトウェア（デスクトップ） =====
(
  'exodus',
  'Exodus',
  'Exodus',
  'software',
  '美しいUIのマルチチェーンデスクトップ・モバイルウォレット。初心者でも使いやすく、取引所機能とウォレットが一体化。Ledger連携にも対応。',
  'https://www.exodus.com',
  'exodus.com',
  '#0B46F9',
  ARRAY['EVM','BTC','SOL','COSMOS'],
  ARRAY['dex_swap','staking','multi_account','mobile_app','ledger_support'],
  'medium',
  7,
  2015,
  false,
  true,
  NULL,
  'デスクトップ・モバイル両対応のマルチチェーンウォレット。'
),
(
  'electrum',
  'Electrum',
  'Electrum',
  'software',
  'Bitcoinに特化した老舗の軽量デスクトップウォレット。ハードウェアウォレットとの連携、マルチシグ対応など上級者向けの機能が充実。',
  'https://electrum.org',
  'electrum.org',
  '#FF6B00',
  ARRAY['BTC'],
  ARRAY['multi_account','ledger_support','trezor_support','open_source','watch_only'],
  'high',
  8,
  2011,
  false,
  true,
  NULL,
  'Bitcoin専用の高機能デスクトップウォレット。'
)

ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  name_en = EXCLUDED.name_en,
  type = EXCLUDED.type,
  description = EXCLUDED.description,
  url = EXCLUDED.url,
  domain = EXCLUDED.domain,
  logo_color = EXCLUDED.logo_color,
  chains = EXCLUDED.chains,
  features = EXCLUDED.features,
  security_level = EXCLUDED.security_level,
  trust_score = EXCLUDED.trust_score,
  established = EXCLUDED.established,
  japanese_support = EXCLUDED.japanese_support,
  is_free = EXCLUDED.is_free,
  price_note = EXCLUDED.price_note,
  notes = EXCLUDED.notes;
