import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = 'https://yjhnsgnvkkqllnnfqoxz.supabase.co';
const SERVICE_KEY = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlqaG5zZ252a2txbGxubmZxb3h6Iiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc3MjQzNTE4MSwiZXhwIjoyMDg4MDExMTgxfQ.ldEodK2JksewHfxOsFYJ1fvL_iHmZXayHoTCiRnsXpo';

const supabase = createClient(SUPABASE_URL, SERVICE_KEY);
const wallets = [
  {
    id: 'metamask',
    name: 'MetaMask',
    name_en: 'MetaMask',
    type: 'browser_extension',
    description: 'Web3のデファクトスタンダード。EVM互換チェーン全般とSolanaに対応し、DeFiやNFTとの互換性が最も広い。ブラウザ拡張・モバイルアプリともに提供。CertiK Skynet: AA (89.77)。',
    url: 'https://metamask.io',
    domain: 'metamask.io',
    logo_color: '#E8831D',
    chains: ['EVM', 'SOL'],
    features: ['dex_swap','nft','staking','multi_account','browser_ext','mobile_app','ledger_support','trezor_support','wc2','open_source'],
    security_level: 'medium',
    trust_score: 9,
    established: 2016,
    japanese_support: false,
    is_free: true,
    price_note: null,
    notes: 'ConsenSysが開発。2,500万人以上のユーザーが利用。スワップ手数料0.875%。',
  },
  {
    id: 'phantom',
    name: 'Phantom',
    name_en: 'Phantom',
    type: 'browser_extension',
    description: 'Solanaエコシステムのデファクトウォレット。リアルタイムの詐欺検知機能を搭載し、EVMチェーンにも対応。NFT管理・DeFi操作・ステーキングをシームレスに利用できる。',
    url: 'https://phantom.app',
    domain: 'phantom.app',
    logo_color: '#AB9FF2',
    chains: ['SOL', 'EVM', 'BTC'],
    features: ['dex_swap','nft','staking','multi_account','browser_ext','mobile_app','ledger_support','wc2'],
    security_level: 'medium',
    trust_score: 9,
    established: 2021,
    japanese_support: false,
    is_free: true,
    price_note: null,
    notes: 'Solanaエコシステムのデファクトスタンダードウォレット。スワップ手数料0.85%。',
  },
  {
    id: 'rabby',
    name: 'Rabby Wallet',
    name_en: 'Rabby Wallet',
    type: 'browser_extension',
    description: 'DeBank製のEVMウォレット。トランザクション事前シミュレーション機能により、フィッシング詐欺やスキャムを事前に検知できるセキュリティ重視設計。',
    url: 'https://rabby.io',
    domain: 'rabby.io',
    logo_color: '#7084FF',
    chains: ['EVM'],
    features: ['dex_swap','nft','multi_account','browser_ext','ledger_support','wc2','open_source'],
    security_level: 'high',
    trust_score: 9,
    established: 2021,
    japanese_support: false,
    is_free: true,
    price_note: null,
    notes: 'DeFiユーザーに人気のセキュリティ重視ウォレット。',
  },
  {
    id: 'coinbase-wallet',
    name: 'Coinbase Wallet',
    name_en: 'Coinbase Wallet',
    type: 'browser_extension',
    description: 'Coinbase提供のセルフカストディウォレット。EVM・Solana・BTC等に対応し、DeFi/NFTの操作が可能。Passkey対応でシードフレーズ不要の設定も可能。CertiK: BBB (73.54)。',
    url: 'https://www.coinbase.com/wallet',
    domain: 'coinbase.com',
    logo_color: '#0052FF',
    chains: ['EVM', 'SOL', 'BTC'],
    features: ['dex_swap','nft','staking','browser_ext','mobile_app','wc2','passkey','open_source'],
    security_level: 'high',
    trust_score: 8,
    established: 2018,
    japanese_support: false,
    is_free: true,
    price_note: null,
    notes: 'Coinbase取引所とシームレスに連携可能。',
  },
  {
    id: 'zerion',
    name: 'Zerion',
    name_en: 'Zerion',
    type: 'browser_extension',
    description: 'DeFiポートフォリオ管理に特化したEVMウォレット。50以上のチェーンと8,000以上のDeFiプロトコルに対応。LP・ステーキング・履歴を一元管理でき、上級DeFiユーザーに人気。',
    url: 'https://zerion.io',
    domain: 'zerion.io',
    logo_color: '#2962EF',
    chains: ['EVM'],
    features: ['dex_swap','nft','staking','multi_account','browser_ext','mobile_app','wc2','watch_only'],
    security_level: 'high',
    trust_score: 9,
    established: 2019,
    japanese_support: false,
    is_free: true,
    price_note: null,
    notes: '50以上のEVMチェーン対応。DeFiポジション・PnL管理が強力。',
  },
  {
    id: 'okx-wallet',
    name: 'OKX Wallet',
    name_en: 'OKX Wallet',
    type: 'browser_extension',
    description: 'OKX取引所が提供するWeb3ウォレット。120以上のネットワークと500以上のDEXに対応したアグリゲーターを内蔵。ミームコイン・NFT・DeFiをワンストップで操作できる。',
    url: 'https://web3.okx.com',
    domain: 'okx.com',
    logo_color: '#000000',
    chains: ['EVM', 'BTC', 'SOL', 'TRON'],
    features: ['dex_swap','nft','staking','multi_account','browser_ext','mobile_app','wc2','watch_only'],
    security_level: 'medium',
    trust_score: 8,
    established: 2022,
    japanese_support: true,
    is_free: true,
    price_note: null,
    notes: '120以上のネットワーク対応。日本語対応あり。OKX取引所との連携が便利。',
  },
  {
    id: 'trust-wallet',
    name: 'Trust Wallet',
    name_en: 'Trust Wallet',
    type: 'mobile',
    description: 'Binance公式のマルチチェーンモバイルウォレット。100以上のブロックチェーン・数百万種類のトークンに対応。NFT・DeFi・ステーキングが一元管理でき、日本語にも対応。CertiK Skynet: AA (91.74)。',
    url: 'https://trustwallet.com',
    domain: 'trustwallet.com',
    logo_color: '#3375BB',
    chains: ['EVM', 'BTC', 'SOL', 'COSMOS', 'NEAR', 'TRON'],
    features: ['dex_swap','nft','staking','multi_account','mobile_app','browser_ext','wc2','open_source'],
    security_level: 'medium',
    trust_score: 9,
    established: 2017,
    japanese_support: true,
    is_free: true,
    price_note: null,
    notes: 'Binance公式ウォレット。日本語対応。オープンソース。',
  },
  {
    id: 'rainbow',
    name: 'Rainbow',
    name_en: 'Rainbow',
    type: 'mobile',
    description: 'シンプルで美しいデザインのEVMモバイルウォレット。NFTの表示やDeFi操作に優れ、初心者にも直感的に使えるUIが特徴。',
    url: 'https://rainbow.me',
    domain: 'rainbow.me',
    logo_color: '#FF6B6B',
    chains: ['EVM'],
    features: ['dex_swap','nft','mobile_app','browser_ext','wc2','open_source'],
    security_level: 'medium',
    trust_score: 7,
    established: 2020,
    japanese_support: false,
    is_free: true,
    price_note: null,
    notes: 'デザイン重視のEthereum向けウォレット。',
  },
  {
    id: 'uniswap-wallet',
    name: 'Uniswap Wallet',
    name_en: 'Uniswap Wallet',
    type: 'mobile',
    description: 'Uniswap Labsが提供するEVMモバイルウォレット。Uniswapとの深い連携により、シームレスなスワップ操作が可能。シンプルで直感的なUI。',
    url: 'https://wallet.uniswap.org',
    domain: 'uniswap.org',
    logo_color: '#FC72FF',
    chains: ['EVM'],
    features: ['dex_swap','nft','mobile_app','wc2','open_source'],
    security_level: 'medium',
    trust_score: 7,
    established: 2023,
    japanese_support: false,
    is_free: true,
    price_note: null,
    notes: 'Uniswap公式ウォレット。DEXスワップに最適化。',
  },
  {
    id: 'zengo',
    name: 'ZenGo',
    name_en: 'ZenGo',
    type: 'mobile',
    description: 'MPC（マルチパーティ計算）技術によりシードフレーズが不要なモバイルウォレット。顔認証・3FAによる高セキュリティ設計で、初心者でも安心して使える。',
    url: 'https://zengo.com',
    domain: 'zengo.com',
    logo_color: '#1A73E8',
    chains: ['EVM', 'BTC', 'SOL'],
    features: ['dex_swap','nft','staking','mobile_app','wc2','passkey'],
    security_level: 'high',
    trust_score: 8,
    established: 2018,
    japanese_support: false,
    is_free: true,
    price_note: 'Proプラン $19.99/月（高度なセキュリティ機能）',
    notes: 'シードフレーズ不要のMPC技術採用。初心者からセキュリティ重視ユーザーまで対応。',
  },
  {
    id: 'exodus',
    name: 'Exodus',
    name_en: 'Exodus',
    type: 'software',
    description: '美しいUIのマルチチェーンデスクトップ・モバイルウォレット。デスクトップ・モバイル・ブラウザ拡張の全プラットフォームに対応。Trezor連携やステーキング機能も充実。CertiK Skynet: A (84.95)。',
    url: 'https://www.exodus.com',
    domain: 'exodus.com',
    logo_color: '#0B46F9',
    chains: ['EVM', 'BTC', 'SOL', 'COSMOS'],
    features: ['dex_swap','nft','staking','multi_account','mobile_app','browser_ext','trezor_support'],
    security_level: 'medium',
    trust_score: 8,
    established: 2015,
    japanese_support: false,
    is_free: true,
    price_note: null,
    notes: 'デスクトップ・モバイル両対応のマルチチェーンウォレット。',
  },
  {
    id: 'electrum',
    name: 'Electrum',
    name_en: 'Electrum',
    type: 'software',
    description: 'Bitcoinに特化した老舗の軽量デスクトップウォレット。2011年から開発が続くオープンソースプロジェクト。ハードウェアウォレット連携・マルチシグ・ウォッチオンリーなど上級者向けの機能が充実。',
    url: 'https://electrum.org',
    domain: 'electrum.org',
    logo_color: '#FF6B00',
    chains: ['BTC'],
    features: ['multi_account','ledger_support','trezor_support','open_source','watch_only'],
    security_level: 'high',
    trust_score: 8,
    established: 2011,
    japanese_support: false,
    is_free: true,
    price_note: null,
    notes: 'Bitcoin専用の高機能デスクトップウォレット。マルチシグ対応。',
  },
];

async function main() {
  console.log(`📦 ${wallets.length}件のウォレットデータを投入します...`);

  const { data, error } = await supabase
    .from('wallets')
    .upsert(wallets, { onConflict: 'id' })
    .select('id');

  if (error) {
    console.error('❌ エラー:', error.message);
    console.error('詳細:', JSON.stringify(error, null, 2));
    process.exit(1);
  }

  console.log(`✅ 成功！ ${data.length}件を upsert しました:`);
  data.forEach(row => console.log(`  - ${row.id}`));
}

main();
